services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kampung-merak-frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
      NODE_ENV: production
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: webserver_proxy
