version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kampung-merak-frontend
    ports:
      - "8084:80"
    restart: always
    environment:
      - NODE_ENV=production
